#!/bin/sh
export GOOGLE_CLIENT_SECRET=T7WotxrJ1gCdTcIQj41IX235
export GOOGLE_CLIENT_ID=441451539007-ihi7u3q4b958f2jelra4ojpv94k2mdi1.apps.googleusercontent.com
export OAUTHLIB_INSECURE_TRANSPORT=1
export OAUTHLIB_RELAX_TOKEN_SCOPE=1
export PYREBASE_API_KEY=AIzaSyAWWFXH-_guyBC-uTmMvaFPD3IV10yeVgw
export PYREBASE_AUTH_DOMAIN=flaskbase.firebaseapp.com
export PYREBASE_DATABASE_URL=https://flaskbase.firebaseio.com
export PYREBASE_STORAGE_BUCKET=flaskbase.appspot.com
export PYREBASE_MESSAGING_SENDER_ID=441451539007
